import type { SupportedLocale } from '@/lib/i18n/locales';

type ExtraCopy = {
  common: {
    review: string;
    published: string;
    publishReview: string;
    open: string;
    noUploadedDocuments: string;
    signInRequired: string;
    accessDenied: string;
  };
  errors: {
    loadProfile: string;
    loadSkippers: string;
    loadMissions: string;
    loadMissionDetails: string;
    loadMessages: string;
    loadApplications: string;
    loadNotifications: string;
    loadRequests: string;
    loadMyMissions: string;
  };
  missionsNew: {
    minFields: string;
    departure: string;
    destination: string;
    startDate: string;
    duration: string;
    compensation: string;
    requirements: string;
    description: string;
  };
  profile: {
    editProfile: string;
    verificationTitle: string;
    chooseDocument: string;
    startEndRequired: string;
    endAfterStart: string;
    photoHttps: string;
    photoTooLarge: string;
    docTooLarge: string;
    docUploaded: string;
    submitReview: string;
    requestSubmitted: string;
    cannotResubmit: string;
    addDocBeforeSubmit: string;
    documentType: string;
    documentFile: string;
    uploadDocument: string;
    submitForVerification: string;
    latestRejection: string;
    currentStatus: string;
    privacyAccount: string;
    privacyAccountBody: string;
    privacyPolicy: string;
    accountDeletion: string;
    docTypeIdentity: string;
    docTypeLicense: string;
    docTypeCertificate: string;
    docTypeCompany: string;
    docTypeOwnership: string;
    docTypeMandate: string;
    docTypeOther: string;
  };
  account: {
    confirmPhraseMismatch: string;
    unableDelete: string;
    deletedRedirecting: string;
  };
  resetPassword: {
    updatedRedirecting: string;
  };
  onboarding: {
    finish: string;
    completeRequired: string;
    profileNotFound: string;
    ready: string;
  };
  notifications: {
    newApplication: string;
    applicationAccepted: string;
    applicationRejected: string;
    missionAssigned: string;
    missionStatusChanged: string;
    newMessage: string;
    generic: string;
    msgNewApplication: string;
    msgApplicationAccepted: string;
    msgApplicationRejected: string;
    msgMissionAssigned: string;
    msgMissionStatusChanged: string;
    msgMissionStatusNow: string;
    msgNewMessage: string;
    msgGeneric: string;
  };
  legal: {
    cgu: { title: string; updated: string; intro: string; bullets: string[] };
    privacy: { title: string; updated: string; body: string; rights: string; account: string };
    cookies: { title: string; updated: string; points: string[] };
    legalNotice: { title: string; updated: string; sections: Array<{ heading: string; body: string }> };
  };
};

const dict: Record<SupportedLocale, ExtraCopy> = {
  fr: {
    common: { review: 'Avis', published: 'Publie.', publishReview: 'Publier un avis', open: 'Ouvrir', noUploadedDocuments: 'Aucun document depose.', signInRequired: 'Connexion requise.', accessDenied: 'Acces refuse.' },
    errors: { loadProfile: 'Impossible de charger le profil.', loadSkippers: 'Impossible de charger les skippers.', loadMissions: 'Impossible de charger les missions.', loadMissionDetails: 'Impossible de charger le detail de la mission.', loadMessages: 'Impossible de charger la messagerie.', loadApplications: 'Impossible de charger les candidatures.', loadNotifications: 'Impossible de charger les notifications.', loadRequests: 'Impossible de charger les demandes.', loadMyMissions: 'Impossible de charger vos missions.' },
    missionsNew: { minFields: 'Merci d indiquer au minimum le lieu et la date.', departure: 'Lieu de depart', destination: 'Destination', startDate: 'Date de debut', duration: 'Duree', compensation: 'Remuneration', requirements: 'Exigences', description: 'Description' },
    profile: {
      editProfile: 'Modifier mon profil', verificationTitle: 'Verification du profil', chooseDocument: 'Merci de choisir un justificatif.',
      startEndRequired: 'Selectionnez une date de debut et une date de fin.', endAfterStart: 'La date de fin doit etre apres la date de debut.',
      photoHttps: 'La photo de profil doit etre une URL HTTPS valide.', photoTooLarge: 'La photo depasse 5 MB.', docTooLarge: 'Le fichier depasse 10 MB.',
      docUploaded: 'Justificatif depose avec succes.', submitReview: 'Soumettre a verification', requestSubmitted: 'Demande envoyee. Un admin va la traiter.',
      cannotResubmit: 'Cette demande ne peut plus etre soumise.', addDocBeforeSubmit: 'Ajoutez au moins un justificatif avant de soumettre.',
      documentType: 'Type de justificatif', documentFile: 'Fichier', uploadDocument: 'Deposer le justificatif', submitForVerification: 'Soumettre a verification', latestRejection: 'Dernier refus', currentStatus: 'Statut actuel', privacyAccount: 'Confidentialite et compte', privacyAccountBody: 'Consultez la politique de confidentialite et la suppression du compte.', privacyPolicy: 'Politique RGPD', accountDeletion: 'Suppression du compte',
      docTypeIdentity: 'Piece d identite', docTypeLicense: 'Permis / licence', docTypeCertificate: 'Certification', docTypeCompany: 'Justificatif societe', docTypeOwnership: 'Justificatif proprietaire', docTypeMandate: 'Mandat broker', docTypeOther: 'Autre'
    },
    account: { confirmPhraseMismatch: 'Saisissez exactement la phrase de confirmation.', unableDelete: 'Impossible de supprimer le compte pour le moment.', deletedRedirecting: 'Compte supprime. Redirection en cours...' },
    resetPassword: { updatedRedirecting: 'Mot de passe mis a jour. Redirection en cours...' },
    onboarding: { finish: 'Terminer l onboarding', completeRequired: 'Merci de completer les informations requises avant de terminer.', profileNotFound: 'Profil introuvable.', ready: 'Tout est pret, vous pouvez terminer l onboarding.' },
    notifications: {
      newApplication: 'Nouvelle candidature', applicationAccepted: 'Candidature acceptee', applicationRejected: 'Candidature refusee', missionAssigned: 'Mission assignee', missionStatusChanged: 'Statut mission modifie', newMessage: 'Nouveau message', generic: 'Notification',
      msgNewApplication: 'Un skipper a postule a votre mission', msgApplicationAccepted: 'Votre candidature a ete acceptee', msgApplicationRejected: 'Votre candidature a ete refusee', msgMissionAssigned: 'Vous avez ete assigne a une mission', msgMissionStatusChanged: 'Le statut de la mission a change.', msgMissionStatusNow: 'Le statut de la mission est maintenant', msgNewMessage: 'Vous avez recu un nouveau message.', msgGeneric: 'Nouvelle notification.'
    },
    legal: {
      cgu: { title: 'Conditions generales d utilisation', updated: 'Derniere mise a jour: 2026-09-08', intro: 'Ces CGU encadrent l utilisation de la plateforme Find a Skipper.', bullets: ['Informations de compte exactes et a jour.', 'Utilisation loyale, sans fraude ni usurpation.', 'Responsabilite individuelle sur les contenus et engagements.'] },
      privacy: { title: 'Confidentialite et RGPD', updated: 'Derniere mise a jour: 2026-09-08', body: 'Nous traitons les donnees necessaires au fonctionnement du service: compte, missions, candidatures, messages et notifications.', rights: 'Vous disposez des droits d acces, rectification, effacement, opposition, limitation et portabilite.', account: 'Gerer la suppression definitive du compte' },
      cookies: { title: 'Politique cookies', updated: 'Derniere mise a jour: 2026-09-08', points: ['Cookies techniques strictement necessaires pour session et securite.', 'Pas de cookies marketing actifs par defaut.', 'Le blocage des cookies essentiels peut degrader certaines fonctions.'] },
      legalNotice: { title: 'Mentions legales', updated: 'Derniere mise a jour: 2026-09-08', sections: [{ heading: 'Editeur', body: 'Find a Skipper. Informations legales detaillees a completer selon votre structure societaire.' }, { heading: 'Hebergement', body: 'Application hebergee sur une infrastructure cloud securisee avec redondance regionale.' }, { heading: 'Propriete intellectuelle', body: 'Les contenus, marques et logos restent proteges. Toute reproduction non autorisee est interdite.' }, { heading: 'Responsabilite', body: 'La plateforme facilite la mise en relation. Chaque partie reste responsable de ses engagements contractuels.' }] }
    }
  },
  en: {
    common: { review: 'Review', published: 'Published.', publishReview: 'Publish review', open: 'Open', noUploadedDocuments: 'No uploaded documents.', signInRequired: 'Sign in required.', accessDenied: 'Access denied.' },
    errors: { loadProfile: 'Unable to load profile.', loadSkippers: 'Unable to load skippers.', loadMissions: 'Unable to load missions.', loadMissionDetails: 'Unable to load mission details.', loadMessages: 'Unable to load messages.', loadApplications: 'Unable to load applications.', loadNotifications: 'Unable to load notifications.', loadRequests: 'Unable to load requests.', loadMyMissions: 'Unable to load your missions.' },
    missionsNew: { minFields: 'Please provide at least departure and date.', departure: 'Departure', destination: 'Destination', startDate: 'Start date', duration: 'Duration', compensation: 'Compensation', requirements: 'Requirements', description: 'Description' },
    profile: { editProfile: 'Edit profile', verificationTitle: 'Profile verification', chooseDocument: 'Please choose a document.', startEndRequired: 'Please select both start and end dates.', endAfterStart: 'End date must be after start date.', photoHttps: 'Profile photo URL must be HTTPS.', photoTooLarge: 'Profile photo exceeds 5 MB.', docTooLarge: 'File exceeds 10 MB.', docUploaded: 'Document uploaded successfully.', submitReview: 'Submit for verification', requestSubmitted: 'Request submitted. An admin will review it.', cannotResubmit: 'This request cannot be submitted again.', addDocBeforeSubmit: 'Add at least one document before submitting.', documentType: 'Document type', documentFile: 'File', uploadDocument: 'Upload document', submitForVerification: 'Submit for verification', latestRejection: 'Latest rejection', currentStatus: 'Current status', privacyAccount: 'Privacy and account', privacyAccountBody: 'Manage privacy and account deletion.', privacyPolicy: 'Privacy policy', accountDeletion: 'Account deletion', docTypeIdentity: 'Identity', docTypeLicense: 'License', docTypeCertificate: 'Certificate', docTypeCompany: 'Company proof', docTypeOwnership: 'Ownership proof', docTypeMandate: 'Broker mandate', docTypeOther: 'Other' },
    account: { confirmPhraseMismatch: 'Please type the confirmation phrase exactly.', unableDelete: 'Unable to delete the account right now.', deletedRedirecting: 'Account deleted. Redirecting...' },
    resetPassword: { updatedRedirecting: 'Password updated. Redirecting...' },
    onboarding: { finish: 'Finish onboarding', completeRequired: 'Please complete required information before finishing.', profileNotFound: 'Profile not found.', ready: 'Everything is ready. You can finish onboarding.' },
    notifications: { newApplication: 'New application', applicationAccepted: 'Application accepted', applicationRejected: 'Application rejected', missionAssigned: 'Mission assigned', missionStatusChanged: 'Mission status updated', newMessage: 'New message', generic: 'Notification', msgNewApplication: 'A skipper applied to your mission', msgApplicationAccepted: 'Your application was accepted', msgApplicationRejected: 'Your application was rejected', msgMissionAssigned: 'You were assigned to a mission', msgMissionStatusChanged: 'Mission status changed.', msgMissionStatusNow: 'Mission status is now', msgNewMessage: 'You received a new message.', msgGeneric: 'New notification.' },
    legal: {
      cgu: { title: 'Terms of use', updated: 'Last update: 2026-09-08', intro: 'These terms govern the use of the Find a Skipper platform.', bullets: ['Keep account information accurate and up to date.', 'Use the platform fairly, without fraud or impersonation.', 'Users remain responsible for their content and commitments.'] },
      privacy: { title: 'Privacy and GDPR', updated: 'Last update: 2026-09-08', body: 'We process data required to run the service: account, missions, applications, messages, and notifications.', rights: 'You have rights of access, correction, deletion, objection, restriction, and portability.', account: 'Manage permanent account deletion' },
      cookies: { title: 'Cookie policy', updated: 'Last update: 2026-09-08', points: ['Strictly necessary technical cookies are used for session and security.', 'No marketing cookies are enabled by default.', 'Blocking essential cookies may reduce some functionality.'] },
      legalNotice: { title: 'Legal notice', updated: 'Last update: 2026-09-08', sections: [{ heading: 'Publisher', body: 'Find a Skipper. Detailed legal company information must be completed for your structure.' }, { heading: 'Hosting', body: 'The application is hosted on secure cloud infrastructure with regional redundancy.' }, { heading: 'Intellectual property', body: 'Content, trademarks, and logos are protected. Unauthorized reuse is prohibited.' }, { heading: 'Liability', body: 'The platform enables matching. Each party remains responsible for contractual commitments.' }] }
    }
  },
  es: {
    common: { review: 'Resena', published: 'Publicado.', publishReview: 'Publicar resena', open: 'Abrir', noUploadedDocuments: 'Sin documentos cargados.', signInRequired: 'Inicia sesion.', accessDenied: 'Acceso denegado.' },
    errors: { loadProfile: 'No se pudo cargar el perfil.', loadSkippers: 'No se pudieron cargar los patrones.', loadMissions: 'No se pudieron cargar las misiones.', loadMissionDetails: 'No se pudo cargar el detalle de la mision.', loadMessages: 'No se pudo cargar la mensajeria.', loadApplications: 'No se pudieron cargar las candidaturas.', loadNotifications: 'No se pudieron cargar las notificaciones.', loadRequests: 'No se pudieron cargar las solicitudes.', loadMyMissions: 'No se pudieron cargar tus misiones.' },
    missionsNew: { minFields: 'Indica al menos salida y fecha.', departure: 'Salida', destination: 'Destino', startDate: 'Fecha de inicio', duration: 'Duracion', compensation: 'Remuneracion', requirements: 'Requisitos', description: 'Descripcion' },
    profile: { editProfile: 'Editar perfil', verificationTitle: 'Verificacion del perfil', chooseDocument: 'Elige un justificante.', startEndRequired: 'Selecciona fecha de inicio y fin.', endAfterStart: 'La fecha fin debe ser posterior al inicio.', photoHttps: 'La foto debe ser URL HTTPS valida.', photoTooLarge: 'La foto supera 5 MB.', docTooLarge: 'El archivo supera 10 MB.', docUploaded: 'Documento subido correctamente.', submitReview: 'Enviar a verificacion', requestSubmitted: 'Solicitud enviada. Un admin la revisara.', cannotResubmit: 'Esta solicitud ya no puede reenviarse.', addDocBeforeSubmit: 'Agrega al menos un documento antes de enviar.', documentType: 'Tipo de documento', documentFile: 'Archivo', uploadDocument: 'Subir documento', submitForVerification: 'Enviar a verificacion', latestRejection: 'Ultimo rechazo', currentStatus: 'Estado actual', privacyAccount: 'Privacidad y cuenta', privacyAccountBody: 'Gestiona privacidad y eliminacion de cuenta.', privacyPolicy: 'Politica de privacidad', accountDeletion: 'Eliminacion de cuenta', docTypeIdentity: 'Identidad', docTypeLicense: 'Licencia', docTypeCertificate: 'Certificado', docTypeCompany: 'Prueba de empresa', docTypeOwnership: 'Prueba de propiedad', docTypeMandate: 'Mandato broker', docTypeOther: 'Otro' },
    account: { confirmPhraseMismatch: 'Escribe exactamente la frase de confirmacion.', unableDelete: 'No se puede eliminar la cuenta ahora.', deletedRedirecting: 'Cuenta eliminada. Redirigiendo...' },
    resetPassword: { updatedRedirecting: 'Contrasena actualizada. Redirigiendo...' },
    onboarding: { finish: 'Finalizar onboarding', completeRequired: 'Completa la informacion requerida antes de finalizar.', profileNotFound: 'Perfil no encontrado.', ready: 'Todo listo. Puedes finalizar onboarding.' },
    notifications: { newApplication: 'Nueva candidatura', applicationAccepted: 'Candidatura aceptada', applicationRejected: 'Candidatura rechazada', missionAssigned: 'Mision asignada', missionStatusChanged: 'Estado de mision actualizado', newMessage: 'Nuevo mensaje', generic: 'Notificacion', msgNewApplication: 'Un patron se postulo a tu mision', msgApplicationAccepted: 'Tu candidatura fue aceptada', msgApplicationRejected: 'Tu candidatura fue rechazada', msgMissionAssigned: 'Has sido asignado a una mision', msgMissionStatusChanged: 'El estado de la mision cambio.', msgMissionStatusNow: 'El estado de la mision ahora es', msgNewMessage: 'Recibiste un nuevo mensaje.', msgGeneric: 'Nueva notificacion.' },
    legal: {
      cgu: { title: 'Condiciones de uso', updated: 'Ultima actualizacion: 2026-09-08', intro: 'Estas condiciones regulan el uso de la plataforma Find a Skipper.', bullets: ['Mantener datos de cuenta exactos.', 'Uso leal, sin fraude ni suplantacion.', 'Responsabilidad individual sobre contenido y compromisos.'] },
      privacy: { title: 'Privacidad y RGPD', updated: 'Ultima actualizacion: 2026-09-08', body: 'Tratamos los datos necesarios para el servicio: cuenta, misiones, candidaturas, mensajes y notificaciones.', rights: 'Dispone de derechos de acceso, rectificacion, supresion, oposicion, limitacion y portabilidad.', account: 'Gestionar la eliminacion permanente de la cuenta' },
      cookies: { title: 'Politica de cookies', updated: 'Ultima actualizacion: 2026-09-08', points: ['Cookies tecnicas necesarias para sesion y seguridad.', 'No hay cookies de marketing activas por defecto.', 'Bloquear cookies esenciales puede degradar funciones.'] },
      legalNotice: { title: 'Aviso legal', updated: 'Ultima actualizacion: 2026-09-08', sections: [{ heading: 'Editor', body: 'Find a Skipper. La informacion legal detallada debe completarse segun su estructura.' }, { heading: 'Alojamiento', body: 'La aplicacion se aloja en una infraestructura cloud segura con redundancia regional.' }, { heading: 'Propiedad intelectual', body: 'Contenido, marcas y logotipos protegidos. Se prohibe la reproduccion no autorizada.' }, { heading: 'Responsabilidad', body: 'La plataforma conecta perfiles. Cada parte sigue siendo responsable de sus compromisos.' }] }
    }
  },
  it: {
    common: { review: 'Recensione', published: 'Pubblicato.', publishReview: 'Pubblica recensione', open: 'Apri', noUploadedDocuments: 'Nessun documento caricato.', signInRequired: 'Accesso richiesto.', accessDenied: 'Accesso negato.' },
    errors: { loadProfile: 'Impossibile caricare il profilo.', loadSkippers: 'Impossibile caricare gli skipper.', loadMissions: 'Impossibile caricare le missioni.', loadMissionDetails: 'Impossibile caricare il dettaglio missione.', loadMessages: 'Impossibile caricare i messaggi.', loadApplications: 'Impossibile caricare le candidature.', loadNotifications: 'Impossibile caricare le notifiche.', loadRequests: 'Impossibile caricare le richieste.', loadMyMissions: 'Impossibile caricare le tue missioni.' },
    missionsNew: { minFields: 'Inserisci almeno partenza e data.', departure: 'Partenza', destination: 'Destinazione', startDate: 'Data inizio', duration: 'Durata', compensation: 'Compenso', requirements: 'Requisiti', description: 'Descrizione' },
    profile: { editProfile: 'Modifica profilo', verificationTitle: 'Verifica profilo', chooseDocument: 'Seleziona un documento.', startEndRequired: 'Seleziona data inizio e fine.', endAfterStart: 'La data fine deve essere successiva.', photoHttps: 'La foto deve essere una URL HTTPS valida.', photoTooLarge: 'La foto supera 5 MB.', docTooLarge: 'Il file supera 10 MB.', docUploaded: 'Documento caricato con successo.', submitReview: 'Invia per verifica', requestSubmitted: 'Richiesta inviata. Un admin la valutera.', cannotResubmit: 'Questa richiesta non puo essere reinviata.', addDocBeforeSubmit: 'Aggiungi almeno un documento prima di inviare.', documentType: 'Tipo documento', documentFile: 'File', uploadDocument: 'Carica documento', submitForVerification: 'Invia per verifica', latestRejection: 'Ultimo rifiuto', currentStatus: 'Stato attuale', privacyAccount: 'Privacy e account', privacyAccountBody: 'Gestisci privacy ed eliminazione account.', privacyPolicy: 'Privacy policy', accountDeletion: 'Eliminazione account', docTypeIdentity: 'Identita', docTypeLicense: 'Licenza', docTypeCertificate: 'Certificato', docTypeCompany: 'Prova societa', docTypeOwnership: 'Prova proprieta', docTypeMandate: 'Mandato broker', docTypeOther: 'Altro' },
    account: { confirmPhraseMismatch: 'Digita esattamente la frase di conferma.', unableDelete: 'Impossibile eliminare l account ora.', deletedRedirecting: 'Account eliminato. Reindirizzamento...' },
    resetPassword: { updatedRedirecting: 'Password aggiornata. Reindirizzamento...' },
    onboarding: { finish: 'Completa onboarding', completeRequired: 'Completa le informazioni richieste prima di terminare.', profileNotFound: 'Profilo non trovato.', ready: 'Tutto pronto. Puoi completare onboarding.' },
    notifications: { newApplication: 'Nuova candidatura', applicationAccepted: 'Candidatura accettata', applicationRejected: 'Candidatura rifiutata', missionAssigned: 'Missione assegnata', missionStatusChanged: 'Stato missione aggiornato', newMessage: 'Nuovo messaggio', generic: 'Notifica', msgNewApplication: 'Uno skipper ha candidato per la tua missione', msgApplicationAccepted: 'La tua candidatura e stata accettata', msgApplicationRejected: 'La tua candidatura e stata rifiutata', msgMissionAssigned: 'Sei stato assegnato a una missione', msgMissionStatusChanged: 'Lo stato della missione e cambiato.', msgMissionStatusNow: 'Lo stato della missione ora e', msgNewMessage: 'Hai ricevuto un nuovo messaggio.', msgGeneric: 'Nuova notifica.' },
    legal: { cgu: { title: 'Condizioni d uso', updated: 'Ultimo aggiornamento: 2026-09-08', intro: 'Queste condizioni regolano l uso della piattaforma Find a Skipper.', bullets: ['Dati account accurati e aggiornati.', 'Uso corretto senza frodi o impersonificazioni.', 'Responsabilita individuale su contenuti e impegni.'] }, privacy: { title: 'Privacy e GDPR', updated: 'Ultimo aggiornamento: 2026-09-08', body: 'Trattiamo i dati necessari al servizio: account, missioni, candidature, messaggi e notifiche.', rights: 'Hai diritti di accesso, rettifica, cancellazione, opposizione, limitazione e portabilita.', account: 'Gestire la cancellazione definitiva dell account' }, cookies: { title: 'Politica cookie', updated: 'Ultimo aggiornamento: 2026-09-08', points: ['Cookie tecnici necessari per sessione e sicurezza.', 'Nessun cookie marketing attivo di default.', 'Il blocco dei cookie essenziali puo ridurre alcune funzioni.'] }, legalNotice: { title: 'Note legali', updated: 'Ultimo aggiornamento: 2026-09-08', sections: [{ heading: 'Editore', body: 'Find a Skipper. Le informazioni legali dettagliate devono essere completate.' }, { heading: 'Hosting', body: 'Applicazione ospitata su infrastruttura cloud sicura con ridondanza regionale.' }, { heading: 'Proprieta intellettuale', body: 'Contenuti, marchi e loghi protetti. Vietata ogni riproduzione non autorizzata.' }, { heading: 'Responsabilita', body: 'La piattaforma facilita il matching. Ogni parte resta responsabile dei propri impegni.' }] } }
  },
  de: {
    common: { review: 'Bewertung', published: 'Veroffentlicht.', publishReview: 'Bewertung veroffentlichen', open: 'Offnen', noUploadedDocuments: 'Keine Dokumente hochgeladen.', signInRequired: 'Anmeldung erforderlich.', accessDenied: 'Zugriff verweigert.' },
    errors: { loadProfile: 'Profil konnte nicht geladen werden.', loadSkippers: 'Skipper konnten nicht geladen werden.', loadMissions: 'Missionen konnten nicht geladen werden.', loadMissionDetails: 'Missionsdetails konnten nicht geladen werden.', loadMessages: 'Nachrichten konnten nicht geladen werden.', loadApplications: 'Bewerbungen konnten nicht geladen werden.', loadNotifications: 'Benachrichtigungen konnten nicht geladen werden.', loadRequests: 'Anfragen konnten nicht geladen werden.', loadMyMissions: 'Ihre Missionen konnten nicht geladen werden.' },
    missionsNew: { minFields: 'Bitte mindestens Abfahrt und Datum angeben.', departure: 'Abfahrt', destination: 'Ziel', startDate: 'Startdatum', duration: 'Dauer', compensation: 'Vergutung', requirements: 'Anforderungen', description: 'Beschreibung' },
    profile: { editProfile: 'Profil bearbeiten', verificationTitle: 'Profilprufung', chooseDocument: 'Bitte Dokument auswahlen.', startEndRequired: 'Bitte Start- und Enddatum wahlen.', endAfterStart: 'Enddatum muss nach Startdatum liegen.', photoHttps: 'Profilfoto muss eine HTTPS-URL sein.', photoTooLarge: 'Profilfoto uberschreitet 5 MB.', docTooLarge: 'Datei uberschreitet 10 MB.', docUploaded: 'Dokument erfolgreich hochgeladen.', submitReview: 'Zur Prufung senden', requestSubmitted: 'Anfrage gesendet. Ein Admin pruft sie.', cannotResubmit: 'Diese Anfrage kann nicht erneut gesendet werden.', addDocBeforeSubmit: 'Mindestens ein Dokument vor dem Senden hinzufugen.', documentType: 'Dokumenttyp', documentFile: 'Datei', uploadDocument: 'Dokument hochladen', submitForVerification: 'Zur Prufung senden', latestRejection: 'Letzte Ablehnung', currentStatus: 'Aktueller Status', privacyAccount: 'Datenschutz und Konto', privacyAccountBody: 'Datenschutz und Kontoloschung verwalten.', privacyPolicy: 'Datenschutzrichtlinie', accountDeletion: 'Kontoloschung', docTypeIdentity: 'Identitat', docTypeLicense: 'Lizenz', docTypeCertificate: 'Zertifikat', docTypeCompany: 'Firmennachweis', docTypeOwnership: 'Eigentumsnachweis', docTypeMandate: 'Broker-Mandat', docTypeOther: 'Andere' },
    account: { confirmPhraseMismatch: 'Bitte den Bestatigungssatz exakt eingeben.', unableDelete: 'Konto kann derzeit nicht geloscht werden.', deletedRedirecting: 'Konto geloscht. Weiterleitung...' },
    resetPassword: { updatedRedirecting: 'Passwort aktualisiert. Weiterleitung...' },
    onboarding: { finish: 'Onboarding abschliessen', completeRequired: 'Bitte erforderliche Angaben vor Abschluss ausfullen.', profileNotFound: 'Profil nicht gefunden.', ready: 'Alles bereit. Onboarding kann abgeschlossen werden.' },
    notifications: { newApplication: 'Neue Bewerbung', applicationAccepted: 'Bewerbung akzeptiert', applicationRejected: 'Bewerbung abgelehnt', missionAssigned: 'Mission zugewiesen', missionStatusChanged: 'Missionsstatus aktualisiert', newMessage: 'Neue Nachricht', generic: 'Benachrichtigung', msgNewApplication: 'Ein Skipper hat sich auf Ihre Mission beworben', msgApplicationAccepted: 'Ihre Bewerbung wurde akzeptiert', msgApplicationRejected: 'Ihre Bewerbung wurde abgelehnt', msgMissionAssigned: 'Ihnen wurde eine Mission zugewiesen', msgMissionStatusChanged: 'Der Missionsstatus wurde geandert.', msgMissionStatusNow: 'Der Missionsstatus ist jetzt', msgNewMessage: 'Sie haben eine neue Nachricht erhalten.', msgGeneric: 'Neue Benachrichtigung.' },
    legal: { cgu: { title: 'Nutzungsbedingungen', updated: 'Letzte aktualisierung: 2026-09-08', intro: 'Diese Bedingungen regeln die Nutzung von Find a Skipper.', bullets: ['Kontodaten korrekt und aktuell halten.', 'Faire Nutzung ohne Betrug oder Identitaetsmissbrauch.', 'Eigenverantwortung fur Inhalte und Zusagen.'] }, privacy: { title: 'Datenschutz und DSGVO', updated: 'Letzte aktualisierung: 2026-09-08', body: 'Wir verarbeiten notwendige Daten fur den Dienst: Konto, Missionen, Bewerbungen, Nachrichten und Benachrichtigungen.', rights: 'Sie haben Rechte auf Auskunft, Berichtigung, Loschung, Widerspruch, Einschrankung und Ubertragbarkeit.', account: 'Dauerhafte Kontoloschung verwalten' }, cookies: { title: 'Cookie-Richtlinie', updated: 'Letzte aktualisierung: 2026-09-08', points: ['Technisch notwendige Cookies fur Sitzung und Sicherheit.', 'Keine Marketing-Cookies standardmassig aktiv.', 'Das Blockieren essenzieller Cookies kann Funktionen beeintrachtigen.'] }, legalNotice: { title: 'Impressum', updated: 'Letzte aktualisierung: 2026-09-08', sections: [{ heading: 'Herausgeber', body: 'Find a Skipper. Detaillierte Rechtsangaben sind je nach Unternehmensform zu erganzen.' }, { heading: 'Hosting', body: 'Die Anwendung lauft auf sicherer Cloud-Infrastruktur mit regionaler Redundanz.' }, { heading: 'Geistiges Eigentum', body: 'Inhalte, Marken und Logos sind geschutzt. Unbefugte Nutzung ist untersagt.' }, { heading: 'Haftung', body: 'Die Plattform vermittelt Kontakte. Jede Partei bleibt fur ihre Verpflichtungen verantwortlich.' }] } }
  },
  pt: {
    common: { review: 'Avaliacao', published: 'Publicado.', publishReview: 'Publicar avaliacao', open: 'Abrir', noUploadedDocuments: 'Sem documentos carregados.', signInRequired: 'Inicie sessao.', accessDenied: 'Acesso negado.' },
    errors: { loadProfile: 'Nao foi possivel carregar o perfil.', loadSkippers: 'Nao foi possivel carregar os skippers.', loadMissions: 'Nao foi possivel carregar as missoes.', loadMissionDetails: 'Nao foi possivel carregar o detalhe da missao.', loadMessages: 'Nao foi possivel carregar as mensagens.', loadApplications: 'Nao foi possivel carregar as candidaturas.', loadNotifications: 'Nao foi possivel carregar as notificacoes.', loadRequests: 'Nao foi possivel carregar os pedidos.', loadMyMissions: 'Nao foi possivel carregar as suas missoes.' },
    missionsNew: { minFields: 'Indique pelo menos partida e data.', departure: 'Partida', destination: 'Destino', startDate: 'Data de inicio', duration: 'Duracao', compensation: 'Remuneracao', requirements: 'Requisitos', description: 'Descricao' },
    profile: { editProfile: 'Editar perfil', verificationTitle: 'Verificacao do perfil', chooseDocument: 'Escolha um documento.', startEndRequired: 'Selecione data de inicio e fim.', endAfterStart: 'A data final deve ser apos a inicial.', photoHttps: 'A foto deve ser um URL HTTPS valido.', photoTooLarge: 'A foto excede 5 MB.', docTooLarge: 'O ficheiro excede 10 MB.', docUploaded: 'Documento carregado com sucesso.', submitReview: 'Submeter para verificacao', requestSubmitted: 'Pedido enviado. Um admin ira analisar.', cannotResubmit: 'Este pedido nao pode ser reenviado.', addDocBeforeSubmit: 'Adicione pelo menos um documento antes de submeter.', documentType: 'Tipo de documento', documentFile: 'Ficheiro', uploadDocument: 'Carregar documento', submitForVerification: 'Submeter para verificacao', latestRejection: 'Ultima rejeicao', currentStatus: 'Estado atual', privacyAccount: 'Privacidade e conta', privacyAccountBody: 'Gerir privacidade e eliminacao da conta.', privacyPolicy: 'Politica de privacidade', accountDeletion: 'Eliminacao da conta', docTypeIdentity: 'Identidade', docTypeLicense: 'Licenca', docTypeCertificate: 'Certificado', docTypeCompany: 'Comprovativo da empresa', docTypeOwnership: 'Comprovativo de propriedade', docTypeMandate: 'Mandato broker', docTypeOther: 'Outro' },
    account: { confirmPhraseMismatch: 'Escreva exatamente a frase de confirmacao.', unableDelete: 'Nao foi possivel eliminar a conta agora.', deletedRedirecting: 'Conta eliminada. A redirecionar...' },
    resetPassword: { updatedRedirecting: 'Senha atualizada. A redirecionar...' },
    onboarding: { finish: 'Concluir onboarding', completeRequired: 'Complete a informacao obrigatoria antes de concluir.', profileNotFound: 'Perfil nao encontrado.', ready: 'Tudo pronto. Pode concluir o onboarding.' },
    notifications: { newApplication: 'Nova candidatura', applicationAccepted: 'Candidatura aceite', applicationRejected: 'Candidatura rejeitada', missionAssigned: 'Missao atribuida', missionStatusChanged: 'Estado da missao atualizado', newMessage: 'Nova mensagem', generic: 'Notificacao', msgNewApplication: 'Um skipper candidatou-se a sua missao', msgApplicationAccepted: 'A sua candidatura foi aceite', msgApplicationRejected: 'A sua candidatura foi rejeitada', msgMissionAssigned: 'Foi atribuido a uma missao', msgMissionStatusChanged: 'O estado da missao mudou.', msgMissionStatusNow: 'O estado da missao e agora', msgNewMessage: 'Recebeu uma nova mensagem.', msgGeneric: 'Nova notificacao.' },
    legal: { cgu: { title: 'Termos de utilizacao', updated: 'Ultima atualizacao: 2026-09-08', intro: 'Estes termos regem o uso da plataforma Find a Skipper.', bullets: ['Dados da conta corretos e atualizados.', 'Uso leal sem fraude ou usurpacao.', 'Responsabilidade individual por conteudos e compromissos.'] }, privacy: { title: 'Privacidade e RGPD', updated: 'Ultima atualizacao: 2026-09-08', body: 'Tratamos dados necessarios ao servico: conta, missoes, candidaturas, mensagens e notificacoes.', rights: 'Tem direitos de acesso, retificacao, eliminacao, oposicao, limitacao e portabilidade.', account: 'Gerir eliminacao definitiva da conta' }, cookies: { title: 'Politica de cookies', updated: 'Ultima atualizacao: 2026-09-08', points: ['Cookies tecnicos necessarios para sessao e seguranca.', 'Sem cookies de marketing ativos por defeito.', 'Bloquear cookies essenciais pode degradar funcionalidades.'] }, legalNotice: { title: 'Aviso legal', updated: 'Ultima atualizacao: 2026-09-08', sections: [{ heading: 'Editor', body: 'Find a Skipper. As informacoes legais detalhadas devem ser completadas.' }, { heading: 'Hospedagem', body: 'Aplicacao hospedada em infraestrutura cloud segura com redundancia regional.' }, { heading: 'Propriedade intelectual', body: 'Conteudos, marcas e logotipos protegidos. Reproducao nao autorizada e proibida.' }, { heading: 'Responsabilidade', body: 'A plataforma facilita conexoes. Cada parte permanece responsavel pelos seus compromissos.' }] } }
  },
  nl: {
    common: { review: 'Beoordeling', published: 'Gepubliceerd.', publishReview: 'Beoordeling publiceren', open: 'Openen', noUploadedDocuments: 'Geen geuploade documenten.', signInRequired: 'Inloggen vereist.', accessDenied: 'Toegang geweigerd.' },
    errors: { loadProfile: 'Kan profiel niet laden.', loadSkippers: 'Kan skippers niet laden.', loadMissions: 'Kan missies niet laden.', loadMissionDetails: 'Kan missiedetails niet laden.', loadMessages: 'Kan berichten niet laden.', loadApplications: 'Kan sollicitaties niet laden.', loadNotifications: 'Kan meldingen niet laden.', loadRequests: 'Kan aanvragen niet laden.', loadMyMissions: 'Kan je missies niet laden.' },
    missionsNew: { minFields: 'Vul minimaal vertrek en datum in.', departure: 'Vertrek', destination: 'Bestemming', startDate: 'Startdatum', duration: 'Duur', compensation: 'Vergoeding', requirements: 'Vereisten', description: 'Beschrijving' },
    profile: { editProfile: 'Profiel bewerken', verificationTitle: 'Profielverificatie', chooseDocument: 'Kies een document.', startEndRequired: 'Selecteer start- en einddatum.', endAfterStart: 'Einddatum moet na startdatum liggen.', photoHttps: 'Profielfoto moet HTTPS URL zijn.', photoTooLarge: 'Foto is groter dan 5 MB.', docTooLarge: 'Bestand groter dan 10 MB.', docUploaded: 'Document succesvol geupload.', submitReview: 'Indienen voor verificatie', requestSubmitted: 'Verzoek verzonden. Een admin zal dit beoordelen.', cannotResubmit: 'Dit verzoek kan niet opnieuw worden ingediend.', addDocBeforeSubmit: 'Voeg minstens een document toe voordat je indient.', documentType: 'Documenttype', documentFile: 'Bestand', uploadDocument: 'Document uploaden', submitForVerification: 'Indienen voor verificatie', latestRejection: 'Laatste afwijzing', currentStatus: 'Huidige status', privacyAccount: 'Privacy en account', privacyAccountBody: 'Beheer privacy en accountverwijdering.', privacyPolicy: 'Privacybeleid', accountDeletion: 'Accountverwijdering', docTypeIdentity: 'Identiteit', docTypeLicense: 'Licentie', docTypeCertificate: 'Certificaat', docTypeCompany: 'Bedrijfsbewijs', docTypeOwnership: 'Eigendomsbewijs', docTypeMandate: 'Broker mandaat', docTypeOther: 'Anders' },
    account: { confirmPhraseMismatch: 'Typ exact de bevestigingszin.', unableDelete: 'Kan account nu niet verwijderen.', deletedRedirecting: 'Account verwijderd. Doorsturen...' },
    resetPassword: { updatedRedirecting: 'Wachtwoord bijgewerkt. Doorsturen...' },
    onboarding: { finish: 'Onboarding afronden', completeRequired: 'Vul verplichte informatie in voor afronden.', profileNotFound: 'Profiel niet gevonden.', ready: 'Alles staat klaar. Je kunt onboarding afronden.' },
    notifications: { newApplication: 'Nieuwe sollicitatie', applicationAccepted: 'Sollicitatie geaccepteerd', applicationRejected: 'Sollicitatie afgewezen', missionAssigned: 'Missie toegewezen', missionStatusChanged: 'Missiestatus bijgewerkt', newMessage: 'Nieuw bericht', generic: 'Melding', msgNewApplication: 'Een skipper solliciteerde op je missie', msgApplicationAccepted: 'Je sollicitatie is geaccepteerd', msgApplicationRejected: 'Je sollicitatie is afgewezen', msgMissionAssigned: 'Je bent toegewezen aan een missie', msgMissionStatusChanged: 'De missiestatus is gewijzigd.', msgMissionStatusNow: 'De missiestatus is nu', msgNewMessage: 'Je hebt een nieuw bericht ontvangen.', msgGeneric: 'Nieuwe melding.' },
    legal: { cgu: { title: 'Gebruiksvoorwaarden', updated: 'Laatste update: 2026-09-08', intro: 'Deze voorwaarden regelen het gebruik van Find a Skipper.', bullets: ['Houd accountgegevens correct en actueel.', 'Eerlijk gebruik zonder fraude of identiteitsmisbruik.', 'Eigen verantwoordelijkheid voor inhoud en afspraken.'] }, privacy: { title: 'Privacy en AVG', updated: 'Laatste update: 2026-09-08', body: 'Wij verwerken gegevens die nodig zijn voor de dienst: account, missies, sollicitaties, berichten en meldingen.', rights: 'Je hebt recht op inzage, correctie, verwijdering, bezwaar, beperking en overdraagbaarheid.', account: 'Permanent account verwijderen beheren' }, cookies: { title: 'Cookiebeleid', updated: 'Laatste update: 2026-09-08', points: ['Noodzakelijke technische cookies voor sessie en beveiliging.', 'Geen marketingcookies standaard actief.', 'Essentiele cookies blokkeren kan functies beperken.'] }, legalNotice: { title: 'Juridische informatie', updated: 'Laatste update: 2026-09-08', sections: [{ heading: 'Uitgever', body: 'Find a Skipper. Gedetailleerde bedrijfsinformatie moet nog worden aangevuld.' }, { heading: 'Hosting', body: 'De applicatie draait op veilige cloudinfrastructuur met regionale redundantie.' }, { heading: 'Intellectueel eigendom', body: 'Inhoud, merken en logos zijn beschermd. Ongeoorloofd gebruik is verboden.' }, { heading: 'Aansprakelijkheid', body: 'Het platform faciliteert matching. Elke partij blijft verantwoordelijk voor afspraken.' }] } }
  },
  el: {
    common: { review: 'Αξιολογηση', published: 'Δημοσιευτηκε.', publishReview: 'Δημοσιευση αξιολογησης', open: 'Ανοιγμα', noUploadedDocuments: 'Δεν υπαρχουν ανεβασμενα εγγραφα.', signInRequired: 'Απαιτειται συνδεση.', accessDenied: 'Δεν επιτρεπεται προσβαση.' },
    errors: { loadProfile: 'Δεν φορτωθηκε το προφιλ.', loadSkippers: 'Δεν φορτωθηκαν οι skippers.', loadMissions: 'Δεν φορτωθηκαν οι αποστολες.', loadMissionDetails: 'Δεν φορτωθηκαν οι λεπτομερειες αποστολης.', loadMessages: 'Δεν φορτωθηκαν τα μηνυματα.', loadApplications: 'Δεν φορτωθηκαν οι αιτησεις.', loadNotifications: 'Δεν φορτωθηκαν οι ειδοποιησεις.', loadRequests: 'Δεν φορτωθηκαν τα αιτηματα.', loadMyMissions: 'Δεν φορτωθηκαν οι αποστολες σας.' },
    missionsNew: { minFields: 'Συμπληρωστε τουλαχιστον αναχωρηση και ημερομηνια.', departure: 'Αναχωρηση', destination: 'Προορισμος', startDate: 'Ημερομηνια εναρξης', duration: 'Διαρκεια', compensation: 'Αμοιβη', requirements: 'Απαιτησεις', description: 'Περιγραφη' },
    profile: { editProfile: 'Επεξεργασια προφιλ', verificationTitle: 'Επαληθευση προφιλ', chooseDocument: 'Επιλεξτε εγγραφο.', startEndRequired: 'Επιλεξτε ημερομηνια εναρξης και ληξης.', endAfterStart: 'Η ληξη πρεπει να ειναι μετα την εναρξη.', photoHttps: 'Η φωτογραφια πρεπει να ειναι HTTPS URL.', photoTooLarge: 'Η φωτογραφια υπερβαινει 5 MB.', docTooLarge: 'Το αρχειο υπερβαινει 10 MB.', docUploaded: 'Το εγγραφο ανεβηκε επιτυχως.', submitReview: 'Υποβολη για επαληθευση', requestSubmitted: 'Το αιτημα σταλθηκε. Θα το ελεγξει διαχειριστης.', cannotResubmit: 'Αυτο το αιτημα δεν μπορει να σταλει ξανα.', addDocBeforeSubmit: 'Προσθεστε τουλαχιστον ενα εγγραφο πριν την υποβολη.', documentType: 'Τυπος εγγραφου', documentFile: 'Αρχειο', uploadDocument: 'Ανεβασμα εγγραφου', submitForVerification: 'Υποβολη για επαληθευση', latestRejection: 'Τελευταια απορριψη', currentStatus: 'Τρεχουσα κατασταση', privacyAccount: 'Απορρητο και λογαριασμος', privacyAccountBody: 'Διαχειριση απορρητου και διαγραφης λογαριασμου.', privacyPolicy: 'Πολιτικη απορρητου', accountDeletion: 'Διαγραφη λογαριασμου', docTypeIdentity: 'Ταυτοτητα', docTypeLicense: 'Αδεια', docTypeCertificate: 'Πιστοποιητικο', docTypeCompany: 'Αποδεικτικο εταιρειας', docTypeOwnership: 'Αποδεικτικο ιδιοκτησιας', docTypeMandate: 'Mandate broker', docTypeOther: 'Αλλο' },
    account: { confirmPhraseMismatch: 'Πληκτρολογηστε ακριβως τη φραση επιβεβαιωσης.', unableDelete: 'Δεν μπορει να διαγραφει ο λογαριασμος τωρα.', deletedRedirecting: 'Ο λογαριασμος διαγραφηκε. Ανακατευθυνση...' },
    resetPassword: { updatedRedirecting: 'Ο κωδικος ενημερωθηκε. Ανακατευθυνση...' },
    onboarding: { finish: 'Ολοκληρωση onboarding', completeRequired: 'Συμπληρωστε τα απαιτουμενα στοιχεια πριν την ολοκληρωση.', profileNotFound: 'Δεν βρεθηκε προφιλ.', ready: 'Ολα ειναι ετοιμα. Μπορειτε να ολοκληρωσετε onboarding.' },
    notifications: { newApplication: 'Νεα αιτηση', applicationAccepted: 'Η αιτηση εγινε αποδεκτη', applicationRejected: 'Η αιτηση απορριφθηκε', missionAssigned: 'Ανατεθηκε αποστολη', missionStatusChanged: 'Ενημερωση καταστασης αποστολης', newMessage: 'Νεο μηνυμα', generic: 'Ειδοποιηση', msgNewApplication: 'Ενας skipper εκανε αιτηση στην αποστολη σας', msgApplicationAccepted: 'Η αιτηση σας εγινε αποδεκτη', msgApplicationRejected: 'Η αιτηση σας απορριφθηκε', msgMissionAssigned: 'Σας ανατεθηκε αποστολη', msgMissionStatusChanged: 'Η κατασταση αποστολης αλλαξε.', msgMissionStatusNow: 'Η κατασταση αποστολης ειναι τωρα', msgNewMessage: 'Λαβατε νεο μηνυμα.', msgGeneric: 'Νεα ειδοποιηση.' },
    legal: { cgu: { title: 'Οροι χρησης', updated: 'Τελευταια ενημερωση: 2026-09-08', intro: 'Οι οροι αυτοι ρυθμιζουν τη χρηση της πλατφορμας Find a Skipper.', bullets: ['Ακριβη και ενημερωμενα στοιχεια λογαριασμου.', 'Δικαιη χρηση χωρις απατη η πλαστοπροσωπια.', 'Ατομικη ευθυνη για περιεχομενο και δεσμευσεις.'] }, privacy: { title: 'Απορρητο και GDPR', updated: 'Τελευταια ενημερωση: 2026-09-08', body: 'Επεξεργαζομαστε δεδομενα που απαιτουνται για την υπηρεσια: λογαριασμο, αποστολες, αιτησεις, μηνυματα, ειδοποιησεις.', rights: 'Διαθετετε δικαιωματα προσβασης, διορθωσης, διαγραφης, αντιρρησης, περιορισμου και φορητοτητας.', account: 'Διαχειριση οριστικης διαγραφης λογαριασμου' }, cookies: { title: 'Πολιτικη cookies', updated: 'Τελευταια ενημερωση: 2026-09-08', points: ['Χρησιμοποιουνται τεχνικα cookies για συνεδρια και ασφαλεια.', 'Δεν ενεργοποιουνται marketing cookies απο προεπιλογη.', 'Η απενεργοποιηση βασικων cookies μπορει να περιορισει λειτουργιες.'] }, legalNotice: { title: 'Νομικες πληροφοριες', updated: 'Τελευταια ενημερωση: 2026-09-08', sections: [{ heading: 'Εκδοτης', body: 'Find a Skipper. Οι αναλυτικες νομικες πληροφοριες πρεπει να συμπληρωθουν.' }, { heading: 'Φιλοξενια', body: 'Η εφαρμογη φιλοξενειται σε ασφαλη cloud υποδομη με γεωγραφικη πλεοναστικοτητα.' }, { heading: 'Πνευματικη ιδιοκτησια', body: 'Περιεχομενο, εμπορικα σηματα και λογοτυπα προστατευονται.' }, { heading: 'Ευθυνη', body: 'Η πλατφορμα διευκολυνει τη συνδεση. Καθε μερος ευθυνεται για τις δεσμευσεις του.' }] } }
  },
  no: {
    common: { review: 'Anmeldelse', published: 'Publisert.', publishReview: 'Publiser anmeldelse', open: 'Aapne', noUploadedDocuments: 'Ingen opplastede dokumenter.', signInRequired: 'Logg inn kreves.', accessDenied: 'Tilgang nektet.' },
    errors: { loadProfile: 'Kunne ikke laste profil.', loadSkippers: 'Kunne ikke laste skippere.', loadMissions: 'Kunne ikke laste oppdrag.', loadMissionDetails: 'Kunne ikke laste oppdragsdetaljer.', loadMessages: 'Kunne ikke laste meldinger.', loadApplications: 'Kunne ikke laste soknader.', loadNotifications: 'Kunne ikke laste varsler.', loadRequests: 'Kunne ikke laste foresporsler.', loadMyMissions: 'Kunne ikke laste dine oppdrag.' },
    missionsNew: { minFields: 'Oppgi minst avreise og dato.', departure: 'Avreise', destination: 'Destinasjon', startDate: 'Startdato', duration: 'Varighet', compensation: 'Betaling', requirements: 'Krav', description: 'Beskrivelse' },
    profile: { editProfile: 'Rediger profil', verificationTitle: 'Profilverifisering', chooseDocument: 'Velg et dokument.', startEndRequired: 'Velg start- og sluttdato.', endAfterStart: 'Sluttdato ma vare etter startdato.', photoHttps: 'Profilbilde ma vare gyldig HTTPS URL.', photoTooLarge: 'Profilbilde overstiger 5 MB.', docTooLarge: 'Fil overstiger 10 MB.', docUploaded: 'Dokument lastet opp.', submitReview: 'Send til verifisering', requestSubmitted: 'Foresporsel sendt. Admin vil behandle den.', cannotResubmit: 'Denne foresporselen kan ikke sendes pa nytt.', addDocBeforeSubmit: 'Legg til minst ett dokument for innsending.', documentType: 'Dokumenttype', documentFile: 'Fil', uploadDocument: 'Last opp dokument', submitForVerification: 'Send til verifisering', latestRejection: 'Siste avvisning', currentStatus: 'Navaerende status', privacyAccount: 'Personvern og konto', privacyAccountBody: 'Administrer personvern og sletting av konto.', privacyPolicy: 'Personvernpolicy', accountDeletion: 'Slett konto', docTypeIdentity: 'Identitet', docTypeLicense: 'Lisens', docTypeCertificate: 'Sertifikat', docTypeCompany: 'Firmadokumentasjon', docTypeOwnership: 'Eierskapsbevis', docTypeMandate: 'Meglermandat', docTypeOther: 'Annet' },
    account: { confirmPhraseMismatch: 'Skriv bekreftelsesfrasen nøyaktig.', unableDelete: 'Kan ikke slette kontoen na.', deletedRedirecting: 'Konto slettet. Omdirigerer...' },
    resetPassword: { updatedRedirecting: 'Passord oppdatert. Omdirigerer...' },
    onboarding: { finish: 'Fullfor onboarding', completeRequired: 'Fyll ut paakrevd informasjon for fullforing.', profileNotFound: 'Profil ikke funnet.', ready: 'Alt er klart. Du kan fullfore onboarding.' },
    notifications: { newApplication: 'Ny soknad', applicationAccepted: 'Soknad akseptert', applicationRejected: 'Soknad avvist', missionAssigned: 'Oppdrag tildelt', missionStatusChanged: 'Oppdragsstatus oppdatert', newMessage: 'Ny melding', generic: 'Varsel', msgNewApplication: 'En skipper sokte pa ditt oppdrag', msgApplicationAccepted: 'Soknaden din ble akseptert', msgApplicationRejected: 'Soknaden din ble avvist', msgMissionAssigned: 'Du ble tildelt et oppdrag', msgMissionStatusChanged: 'Oppdragsstatus ble endret.', msgMissionStatusNow: 'Oppdragsstatus er na', msgNewMessage: 'Du har mottatt en ny melding.', msgGeneric: 'Nytt varsel.' },
    legal: { cgu: { title: 'Bruksvilkar', updated: 'Sist oppdatert: 2026-09-08', intro: 'Disse vilkarene regulerer bruk av Find a Skipper.', bullets: ['Hold kontoinformasjon korrekt og oppdatert.', 'Rettferdig bruk uten svindel eller identitetsmisbruk.', 'Individuelt ansvar for innhold og forpliktelser.'] }, privacy: { title: 'Personvern og GDPR', updated: 'Sist oppdatert: 2026-09-08', body: 'Vi behandler data som er nodvendige for tjenesten: konto, oppdrag, soknader, meldinger og varsler.', rights: 'Du har rett til innsyn, retting, sletting, innsigelse, begrensning og dataportabilitet.', account: 'Administrer permanent sletting av konto' }, cookies: { title: 'Cookiepolicy', updated: 'Sist oppdatert: 2026-09-08', points: ['Tekniske nodvendige cookies brukes for sesjon og sikkerhet.', 'Ingen markedsforingscookies er aktive som standard.', 'Blokkering av essensielle cookies kan redusere funksjonalitet.'] }, legalNotice: { title: 'Juridisk informasjon', updated: 'Sist oppdatert: 2026-09-08', sections: [{ heading: 'Utgiver', body: 'Find a Skipper. Detaljert juridisk selskapsinformasjon ma fylles ut.' }, { heading: 'Hosting', body: 'Applikasjonen hostes pa sikker skyinfrastruktur med regional redundans.' }, { heading: 'Immaterielle rettigheter', body: 'Innhold, varemerker og logoer er beskyttet.' }, { heading: 'Ansvar', body: 'Plattformen legger til rette for matching. Partene er ansvarlige for egne avtaler.' }] } }
  },
  da: {
    common: { review: 'Anmeldelse', published: 'Udgivet.', publishReview: 'Udgiv anmeldelse', open: 'Aabn', noUploadedDocuments: 'Ingen uploadede dokumenter.', signInRequired: 'Log ind paakraevet.', accessDenied: 'Adgang afvist.' },
    errors: { loadProfile: 'Kunne ikke indlaese profil.', loadSkippers: 'Kunne ikke indlaese skippere.', loadMissions: 'Kunne ikke indlaese missioner.', loadMissionDetails: 'Kunne ikke indlaese missionsdetaljer.', loadMessages: 'Kunne ikke indlaese beskeder.', loadApplications: 'Kunne ikke indlaese ansogninger.', loadNotifications: 'Kunne ikke indlaese notifikationer.', loadRequests: 'Kunne ikke indlaese anmodninger.', loadMyMissions: 'Kunne ikke indlaese dine missioner.' },
    missionsNew: { minFields: 'Angiv mindst afgang og dato.', departure: 'Afgang', destination: 'Destination', startDate: 'Startdato', duration: 'Varighed', compensation: 'Betaling', requirements: 'Krav', description: 'Beskrivelse' },
    profile: { editProfile: 'Rediger profil', verificationTitle: 'Profilverificering', chooseDocument: 'Vae lg et dokument.', startEndRequired: 'Vae lg start- og slutdato.', endAfterStart: 'Slutdato skal vaere efter startdato.', photoHttps: 'Profilfoto skal vaere gyldig HTTPS URL.', photoTooLarge: 'Profilfoto overstiger 5 MB.', docTooLarge: 'Fil overstiger 10 MB.', docUploaded: 'Dokument uploadet.', submitReview: 'Send til verificering', requestSubmitted: 'Anmodning sendt. En admin vil gennemga den.', cannotResubmit: 'Denne anmodning kan ikke sendes igen.', addDocBeforeSubmit: 'Tilfoj mindst et dokument for afsendelse.', documentType: 'Dokumenttype', documentFile: 'Fil', uploadDocument: 'Upload dokument', submitForVerification: 'Send til verificering', latestRejection: 'Seneste afvisning', currentStatus: 'Nuvaerende status', privacyAccount: 'Privatliv og konto', privacyAccountBody: 'Administrer privatliv og kontosletning.', privacyPolicy: 'Privatlivspolitik', accountDeletion: 'Kontosletning', docTypeIdentity: 'Identitet', docTypeLicense: 'Licens', docTypeCertificate: 'Certifikat', docTypeCompany: 'Virksomhedsbevis', docTypeOwnership: 'Ejerbevis', docTypeMandate: 'Broker-mandat', docTypeOther: 'Andet' },
    account: { confirmPhraseMismatch: 'Indtast bekraeftelsesfrasen praecist.', unableDelete: 'Kan ikke slette konto lige nu.', deletedRedirecting: 'Konto slettet. Omdirigerer...' },
    resetPassword: { updatedRedirecting: 'Adgangskode opdateret. Omdirigerer...' },
    onboarding: { finish: 'Faerdigor onboarding', completeRequired: 'Udfyld noedvendige oplysninger for faerdigor.', profileNotFound: 'Profil ikke fundet.', ready: 'Alt er klart. Du kan faerdiggore onboarding.' },
    notifications: { newApplication: 'Ny ansogning', applicationAccepted: 'Ansogning accepteret', applicationRejected: 'Ansogning afvist', missionAssigned: 'Mission tildelt', missionStatusChanged: 'Missionsstatus opdateret', newMessage: 'Ny besked', generic: 'Notifikation', msgNewApplication: 'En skipper ansogte om din mission', msgApplicationAccepted: 'Din ansogning blev accepteret', msgApplicationRejected: 'Din ansogning blev afvist', msgMissionAssigned: 'Du blev tildelt en mission', msgMissionStatusChanged: 'Missionsstatus blev aendret.', msgMissionStatusNow: 'Missionsstatus er nu', msgNewMessage: 'Du har modtaget en ny besked.', msgGeneric: 'Ny notifikation.' },
    legal: { cgu: { title: 'Brugsvilkar', updated: 'Sidst opdateret: 2026-09-08', intro: 'Disse vilkar regulerer brugen af Find a Skipper.', bullets: ['Hold kontooplysninger korrekte og opdaterede.', 'Fair brug uden svindel eller identitetsmisbrug.', 'Individuelt ansvar for indhold og forpligtelser.'] }, privacy: { title: 'Privatliv og GDPR', updated: 'Sidst opdateret: 2026-09-08', body: 'Vi behandler data, der er nodvendige for tjenesten: konto, missioner, ansogninger, beskeder og notifikationer.', rights: 'Du har ret til indsigt, rettelse, sletning, indsigelse, begransning og dataportabilitet.', account: 'Administrer permanent kontosletning' }, cookies: { title: 'Cookiepolitik', updated: 'Sidst opdateret: 2026-09-08', points: ['Tekniske nodvendige cookies bruges til session og sikkerhed.', 'Ingen marketingcookies er aktive som standard.', 'Blokering af essentielle cookies kan reducere funktionalitet.'] }, legalNotice: { title: 'Juridisk information', updated: 'Sidst opdateret: 2026-09-08', sections: [{ heading: 'Udgiver', body: 'Find a Skipper. Detaljerede juridiske virksomhedsoplysninger skal udfyldes.' }, { heading: 'Hosting', body: 'Applikationen hostes pa sikker cloud-infrastruktur med regional redundans.' }, { heading: 'Intellektuel ejendom', body: 'Indhold, varemarker og logoer er beskyttede.' }, { heading: 'Ansvar', body: 'Platformen formidler kontakt. Hver part har ansvar for egne forpligtelser.' }] } }
  },
};

export function getExtraCopy(locale: SupportedLocale) {
  return dict[locale];
}
